# Copyright (c) 2010-2011 Robin Jarry
#
# This file is part of EVE Corporation Management.
#
# EVE Corporation Management is free software: you can redistribute it and/or
# modify it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or (at your
# option) any later version.
#
# EVE Corporation Management is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of MERCHANTABILITY
# or FITNESS FOR A PARTICULAR PURPOSE. See the GNU General Public License for
# more details.
#
# You should have received a copy of the GNU General Public License along with
# EVE Corporation Management. If not, see <http://www.gnu.org/licenses/>.

__date__ = "2011 11 2"
__author__ = "diabeteman"


STRONTIUM_CLATHRATES_TYPEID = 16275

CHARTER_MIN_SEC_STATUS = 0.45

SILO_TYPEID = 14343
SILO_VOLUME = 20000.0

CALDARI_FUEL_BLOCK_TYPEID = 4051
MINMATAR_FUEL_BLOCK_TYPEID = 4246
AMARR_FUEL_BLOCK_TYPEID = 4247
GALLENTE_FUEL_BLOCK_TYPEID = 4312

AMARR_EMPIRE_STARBASE_CHARTER = 24592
AMMATAR_MANDATE_STARBASE_CHARTER = 24597
CALDARI_STATE_STARBASE_CHARTER = 24593
GALLENTE_FEDERATION_STARBASE_CHARTER = 24594
KHANID_KINGDOM_STARBASE_CHARTER = 24596
MINMATAR_REPUBLIC_STARBASE_CHARTER = 24595

CALDARI_RACEID = 1
MINMATAR_RACEID = 2
AMARR_RACEID = 4
GALLENTE_RACEID = 8

RACE_TO_FUEL = {
    CALDARI_RACEID: CALDARI_FUEL_BLOCK_TYPEID,
    MINMATAR_RACEID: MINMATAR_FUEL_BLOCK_TYPEID,
    AMARR_RACEID: AMARR_FUEL_BLOCK_TYPEID,
    GALLENTE_RACEID: GALLENTE_FUEL_BLOCK_TYPEID,
}
FUEL_TO_RACE = {
    CALDARI_FUEL_BLOCK_TYPEID: CALDARI_RACEID,
    MINMATAR_FUEL_BLOCK_TYPEID: MINMATAR_RACEID,
    AMARR_FUEL_BLOCK_TYPEID: AMARR_RACEID,
    GALLENTE_FUEL_BLOCK_TYPEID: GALLENTE_RACEID,
}
RACEID_TO_CHARTERID = {
    500001: CALDARI_STATE_STARBASE_CHARTER,
    500002: MINMATAR_REPUBLIC_STARBASE_CHARTER,
    500003: AMARR_EMPIRE_STARBASE_CHARTER,
    500004: GALLENTE_FEDERATION_STARBASE_CHARTER,
    500007: AMMATAR_MANDATE_STARBASE_CHARTER,
    500008: KHANID_KINGDOM_STARBASE_CHARTER,
}
